#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("R2G_Clientes.Resource", IsApplication=true)]

namespace R2G_Clientes
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Auth0.SDK.Resource.String.library_name = global::R2G_Clientes.Resource.String.library_name;
			global::SQLite.Resource.String.ApplicationName = global::R2G_Clientes.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::R2G_Clientes.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int cartypes = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int rapid_logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int rapilogo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Untitled = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070031
			public const int achdeposit = 2131165233;
			
			// aapt resource value: 0x7f070030
			public const int bankDeposit = 2131165232;
			
			// aapt resource value: 0x7f070002
			public const int buttDone = 2131165186;
			
			// aapt resource value: 0x7f07002d
			public const int button1 = 2131165229;
			
			// aapt resource value: 0x7f070037
			public const int callOfficeforChanges = 2131165239;
			
			// aapt resource value: 0x7f070023
			public const int cars = 2131165219;
			
			// aapt resource value: 0x7f070032
			public const int cash = 2131165234;
			
			// aapt resource value: 0x7f070010
			public const int checkBox1 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int checkBox2 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int checkBox3 = 2131165202;
			
			// aapt resource value: 0x7f070019
			public const int checkBox4 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int checkBox5 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int checkBox6 = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int checkBox7 = 2131165212;
			
			// aapt resource value: 0x7f070025
			public const int config = 2131165221;
			
			// aapt resource value: 0x7f07002f
			public const int creditCard = 2131165231;
			
			// aapt resource value: 0x7f070022
			public const int details = 2131165218;
			
			// aapt resource value: 0x7f07001f
			public const int done = 2131165215;
			
			// aapt resource value: 0x7f070016
			public const int editButt = 2131165206;
			
			// aapt resource value: 0x7f070003
			public const int editText1 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int editText2 = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int editText3 = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int editText4 = 2131165196;
			
			// aapt resource value: 0x7f070014
			public const int editText5 = 2131165204;
			
			// aapt resource value: 0x7f070038
			public const int editText6 = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int editText7 = 2131165241;
			
			// aapt resource value: 0x7f07003b
			public const int editText8 = 2131165243;
			
			// aapt resource value: 0x7f070018
			public const int getmehome = 2131165208;
			
			// aapt resource value: 0x7f07002e
			public const int googlePayment = 2131165230;
			
			// aapt resource value: 0x7f070024
			public const int history = 2131165220;
			
			// aapt resource value: 0x7f070020
			public const int imageView1 = 2131165216;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout1 = 2131165191;
			
			// aapt resource value: 0x7f070033
			public const int load = 2131165235;
			
			// aapt resource value: 0x7f070021
			public const int purchase = 2131165217;
			
			// aapt resource value: 0x7f070028
			public const int radioButton1 = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int radioButton2 = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int radioButton3 = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int radioButton4 = 2131165227;
			
			// aapt resource value: 0x7f070027
			public const int radioGroup1 = 2131165223;
			
			// aapt resource value: 0x7f07003d
			public const int register = 2131165245;
			
			// aapt resource value: 0x7f070005
			public const int save = 2131165189;
			
			// aapt resource value: 0x7f070015
			public const int saveButt = 2131165205;
			
			// aapt resource value: 0x7f070006
			public const int scrollView1 = 2131165190;
			
			// aapt resource value: 0x7f070017
			public const int showme = 2131165207;
			
			// aapt resource value: 0x7f07003c
			public const int signIn = 2131165244;
			
			// aapt resource value: 0x7f070036
			public const int signin = 2131165238;
			
			// aapt resource value: 0x7f070035
			public const int signout = 2131165237;
			
			// aapt resource value: 0x7f070034
			public const int space1 = 2131165236;
			
			// aapt resource value: 0x7f070026
			public const int space2 = 2131165222;
			
			// aapt resource value: 0x7f07000e
			public const int spinner1 = 2131165198;
			
			// aapt resource value: 0x7f07001d
			public const int submitButt = 2131165213;
			
			// aapt resource value: 0x7f07002c
			public const int submitbutt = 2131165228;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f07003a
			public const int textView10 = 2131165242;
			
			// aapt resource value: 0x7f070001
			public const int textView2 = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int textView3 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int textView4 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int textView5 = 2131165195;
			
			// aapt resource value: 0x7f07000f
			public const int textView6 = 2131165199;
			
			// aapt resource value: 0x7f070013
			public const int textView7 = 2131165203;
			
			// aapt resource value: 0x7f07000d
			public const int textView8 = 2131165197;
			
			// aapt resource value: 0x7f07001e
			public const int textView9 = 2131165214;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_banki_ach = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_car_detail_change = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_car_register = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_cash = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_details = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_details_changed = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int activity_menu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int activity_packages = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int activity_payment_bank_transaction = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int activity_payment_credit_card = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int activity_payment_options = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int activity_purchase_details = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int activity_service_history = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int activity_settings = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int activity_splash = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int activity_user_register = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Main = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040073
			public const int ApplicationName = 2130968691;
			
			// aapt resource value: 0x7f040072
			public const int Hello = 2130968690;
			
			// aapt resource value: 0x7f040029
			public const int address = 2130968617;
			
			// aapt resource value: 0x7f04004b
			public const int allDone = 2130968651;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040014
			public const int availablepacks = 2130968596;
			
			// aapt resource value: 0x7f040025
			public const int bankACH = 2130968613;
			
			// aapt resource value: 0x7f040024
			public const int bankDep = 2130968612;
			
			// aapt resource value: 0x7f040026
			public const int basics = 2130968614;
			
			// aapt resource value: 0x7f040044
			public const int car = 2130968644;
			
			// aapt resource value: 0x7f040008
			public const int carRegister = 2130968584;
			
			// aapt resource value: 0x7f040031
			public const int carcolor = 2130968625;
			
			// aapt resource value: 0x7f040030
			public const int carmake = 2130968624;
			
			// aapt resource value: 0x7f040032
			public const int carmodel = 2130968626;
			
			// aapt resource value: 0x7f040071
			public const int cartype = 2130968689;
			
			// aapt resource value: 0x7f04003d
			public const int cash = 2130968637;
			
			// aapt resource value: 0x7f040038
			public const int comments = 2130968632;
			
			// aapt resource value: 0x7f04004c
			public const int confirmation = 2130968652;
			
			// aapt resource value: 0x7f04003c
			public const int contact = 2130968636;
			
			// aapt resource value: 0x7f040023
			public const int credit = 2130968611;
			
			// aapt resource value: 0x7f040007
			public const int details = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int done = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int edit = 2130968589;
			
			// aapt resource value: 0x7f040028
			public const int email = 2130968616;
			
			// aapt resource value: 0x7f040036
			public const int endnotif = 2130968630;
			
			// aapt resource value: 0x7f040070
			public const int fail = 2130968688;
			
			// aapt resource value: 0x7f040019
			public const int finishTime = 2130968601;
			
			// aapt resource value: 0x7f040058
			public const int fourlargesingle = 2130968664;
			
			// aapt resource value: 0x7f040064
			public const int fourmedpack = 2130968676;
			
			// aapt resource value: 0x7f040054
			public const int fourmedsingle = 2130968660;
			
			// aapt resource value: 0x7f04000e
			public const int fourservices = 2130968590;
			
			// aapt resource value: 0x7f040068
			public const int fourslargepack = 2130968680;
			
			// aapt resource value: 0x7f040060
			public const int foursmallpack = 2130968672;
			
			// aapt resource value: 0x7f040050
			public const int foursmallsingle = 2130968656;
			
			// aapt resource value: 0x7f04006c
			public const int fourxtralaregpack = 2130968684;
			
			// aapt resource value: 0x7f04005c
			public const int fourxtralargesingle = 2130968668;
			
			// aapt resource value: 0x7f04001e
			public const int fri = 2130968606;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040012
			public const int history = 2130968594;
			
			// aapt resource value: 0x7f040074
			public const int library_name = 2130968692;
			
			// aapt resource value: 0x7f04002f
			public const int licenseplate = 2130968623;
			
			// aapt resource value: 0x7f040015
			public const int locations = 2130968597;
			
			// aapt resource value: 0x7f040040
			public const int loginSuccess = 2130968640;
			
			// aapt resource value: 0x7f04003b
			public const int logout = 2130968635;
			
			// aapt resource value: 0x7f04003e
			public const int mainmenu = 2130968638;
			
			// aapt resource value: 0x7f04001a
			public const int mon = 2130968602;
			
			// aapt resource value: 0x7f040027
			public const int name = 2130968615;
			
			// aapt resource value: 0x7f04000c
			public const int next = 2130968588;
			
			// aapt resource value: 0x7f040039
			public const int notavailable = 2130968633;
			
			// aapt resource value: 0x7f040034
			public const int notifications = 2130968628;
			
			// aapt resource value: 0x7f04003a
			public const int notyet = 2130968634;
			
			// aapt resource value: 0x7f04004a
			public const int officeaddress = 2130968650;
			
			// aapt resource value: 0x7f040045
			public const int orderComms = 2130968645;
			
			// aapt resource value: 0x7f040047
			public const int orderPack = 2130968647;
			
			// aapt resource value: 0x7f040046
			public const int orderdays = 2130968646;
			
			// aapt resource value: 0x7f040049
			public const int ordersummary = 2130968649;
			
			// aapt resource value: 0x7f040048
			public const int ordertotal = 2130968648;
			
			// aapt resource value: 0x7f040041
			public const int ordrID = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int ordraddrs = 2130968642;
			
			// aapt resource value: 0x7f040033
			public const int packageselect = 2130968627;
			
			// aapt resource value: 0x7f040006
			public const int packs = 2130968582;
			
			// aapt resource value: 0x7f040013
			public const int packsamounts = 2130968595;
			
			// aapt resource value: 0x7f040005
			public const int password = 2130968581;
			
			// aapt resource value: 0x7f040021
			public const int paymentoptions = 2130968609;
			
			// aapt resource value: 0x7f04004d
			public const int payplz = 2130968653;
			
			// aapt resource value: 0x7f04002a
			public const int phone = 2130968618;
			
			// aapt resource value: 0x7f040003
			public const int register = 2130968579;
			
			// aapt resource value: 0x7f04001f
			public const int sat = 2130968607;
			
			// aapt resource value: 0x7f04000a
			public const int save = 2130968586;
			
			// aapt resource value: 0x7f040016
			public const int servicedays = 2130968598;
			
			// aapt resource value: 0x7f040009
			public const int settings = 2130968585;
			
			// aapt resource value: 0x7f04003f
			public const int showme = 2130968639;
			
			// aapt resource value: 0x7f040002
			public const int signin = 2130968578;
			
			// aapt resource value: 0x7f04000f
			public const int sixServices = 2130968591;
			
			// aapt resource value: 0x7f040069
			public const int sixlargepack = 2130968681;
			
			// aapt resource value: 0x7f040059
			public const int sixlargesingle = 2130968665;
			
			// aapt resource value: 0x7f040065
			public const int sixmedpack = 2130968677;
			
			// aapt resource value: 0x7f040055
			public const int sixmedsingle = 2130968661;
			
			// aapt resource value: 0x7f040061
			public const int sixsmallpack = 2130968673;
			
			// aapt resource value: 0x7f040051
			public const int sixsmallsingle = 2130968657;
			
			// aapt resource value: 0x7f04006d
			public const int sixxtralargepack = 2130968685;
			
			// aapt resource value: 0x7f04005d
			public const int sixxtralargsingle = 2130968669;
			
			// aapt resource value: 0x7f040037
			public const int specialsnotif = 2130968631;
			
			// aapt resource value: 0x7f040018
			public const int startTime = 2130968600;
			
			// aapt resource value: 0x7f040035
			public const int startnotf = 2130968629;
			
			// aapt resource value: 0x7f040020
			public const int sun = 2130968608;
			
			// aapt resource value: 0x7f04004e
			public const int takeme = 2130968654;
			
			// aapt resource value: 0x7f04004f
			public const int takemepolite = 2130968655;
			
			// aapt resource value: 0x7f040010
			public const int tenServices = 2130968592;
			
			// aapt resource value: 0x7f04006a
			public const int tenlargepack = 2130968682;
			
			// aapt resource value: 0x7f04005a
			public const int tenlargesinge = 2130968666;
			
			// aapt resource value: 0x7f040066
			public const int tenmedpack = 2130968678;
			
			// aapt resource value: 0x7f040056
			public const int tenmedsinge = 2130968662;
			
			// aapt resource value: 0x7f040062
			public const int tensmallpack = 2130968674;
			
			// aapt resource value: 0x7f040052
			public const int tensmallsinge = 2130968658;
			
			// aapt resource value: 0x7f04006e
			public const int tenxtralargepack = 2130968686;
			
			// aapt resource value: 0x7f04005e
			public const int tenxtralargsinge = 2130968670;
			
			// aapt resource value: 0x7f04001d
			public const int thu = 2130968605;
			
			// aapt resource value: 0x7f040017
			public const int timewindow = 2130968599;
			
			// aapt resource value: 0x7f040043
			public const int tmewndow = 2130968643;
			
			// aapt resource value: 0x7f04001b
			public const int tue = 2130968603;
			
			// aapt resource value: 0x7f040011
			public const int twelveServices = 2130968593;
			
			// aapt resource value: 0x7f04006b
			public const int twelvelargepack = 2130968683;
			
			// aapt resource value: 0x7f04005b
			public const int twelvelargesingle = 2130968667;
			
			// aapt resource value: 0x7f040067
			public const int twelvemedpack = 2130968679;
			
			// aapt resource value: 0x7f040057
			public const int twelvemedsingle = 2130968663;
			
			// aapt resource value: 0x7f040063
			public const int twelvesmallpack = 2130968675;
			
			// aapt resource value: 0x7f040053
			public const int twelvesmallsingle = 2130968659;
			
			// aapt resource value: 0x7f04006f
			public const int twelvextralargepack = 2130968687;
			
			// aapt resource value: 0x7f04005f
			public const int twelvextralargsingle = 2130968671;
			
			// aapt resource value: 0x7f040004
			public const int username = 2130968580;
			
			// aapt resource value: 0x7f040022
			public const int wallet = 2130968610;
			
			// aapt resource value: 0x7f04001c
			public const int wed = 2130968604;
			
			// aapt resource value: 0x7f04002c
			public const int workAddress = 2130968620;
			
			// aapt resource value: 0x7f04002b
			public const int workDetails = 2130968619;
			
			// aapt resource value: 0x7f04002d
			public const int workEmail = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int workPhone = 2130968622;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
