// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Web;
using System.Json;
using System.Net;

using R2G_Clientes.Shared;
using Newtonsoft.Json;

using Foundation;

using UIKit;
using UIKit;

namespace R2G_Clients.iOS
{
	public partial class UsrLoginViewController : UIViewController
	{
		public UsrLoginViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			btnLogIn.TouchUpInside += async (object sender, EventArgs e) => {
				
			};
		}

		public string urlbuilder(){
			string baseurl = "http://ps413027.dreamhost.com:8080/rapidtoREST/service/users/login";



		}

	}
}
